Vite migration
knowit/kompetansekartlegging-app pull request #144
Opened 2023-03-28 09:32 UTC by synnovsh

Closes #142

2023-03-29 09:59 UTC, krisstam reviewed
Jeg skal ta en sjekk på dette etterhvert, men foreløpig så ser det veldig lovende ut

2023-03-29 10:17 UTC, synnovsh commented
Når man kjører dette lokalt får man flere warnings i konsollen, men dette fikses ved oppgradering til React 17 som jeg tar i en ny PR

2023-03-29 11:49 UTC, andersrebner requested changes

2023-03-29 11:49 UTC, andersrebner commented on frontend/package.json
> +      "@typescript-eslint/no-unused-vars": "off"
Denne skrur av `no-unused-vars`-regelen helt, min subjektive mening er at vi bør ha den aktiv.
Ser at vi da får 21 nye warnings, men mange av dem er greie å fikse.
Inkluderer en del ubrukte props, så det kan sikkert være greit med en opprydding.

Kan jo evt. branche ut herfra så vi får en PR kun med lint-fixes 😄

2023-03-29 12:11 UTC, andersrebner commented
Ser bra ut! Merkbart hvor mye raskere dev-serveren starter 🚀

2023-03-30 07:21 UTC, andersrebner commented on frontend/package.json
> +      "@typescript-eslint/no-unused-vars": "off"
Den reagerte på færre caser med react-scripts, men var ikke av. Nå har den blitt hakket hissigere 🚨

2023-03-30 08:03 UTC, synnovsh commented on frontend/package.json
> +      "@typescript-eslint/no-unused-vars": "off"
Interessant! Lurer på hva @krisstam synes-- skal det i egen branch eller fikses i denne?

2023-04-05 11:07 UTC, krisstam approved these changes
Endelig litt tid til å teste ut. Ser veldig bra ut dette, og fikk ingen  problemer når jeg satt opp prosjektet på laptopen min, så da får jeg vel endelig Approve 😄

2023-04-05 11:07 UTC, krisstam commented on frontend/package.json
> +      "@typescript-eslint/no-unused-vars": "off"
Jeg synes det går helt fint å ta det med i denne PR-en, men det er også helt greit å ta det i en egen PR :)
Jeg er også enig i at no-unused-vars er en fin linting-regel å ha på

2023-04-06 10:26 UTC, andersrebner approved these changes

2023-04-07 15:57 UTC, merged

2023-04-07 16:14 UTC, synnovsh commented
https://github.com/danny-avila/chatgpt-clone/issues/170