WIP: Anonymization
knowit/kompetansekartlegging-app pull request #180
Opened 2023-05-04 11:10 UTC by andersrebner

2023-05-26 09:57 UTC, synnovsh commented on frontend/src/components/AdminPanel/AnonymizeUsers.tsx
> +    setMutationError(null)
setMutationError => setError

2023-05-26 09:57 UTC, synnovsh commented on frontend/src/components/AdminPanel/adminApi.tsx
> +    console.log(e)
Vil vi beholde?

2023-05-26 09:57 UTC, synnovsh commented on frontend/src/components/AdminPanel/adminApi.tsx
> +  const myInit = {
endre navn

2023-05-26 11:26 UTC, andersrebner commented on cdk/backend/function/AdminQueries/app.js
> +    .json({ custom_error: err.message })
La det stå som det var gitt at det fungerer

2023-05-26 11:29 UTC, andersrebner commented on cdk/backend/function/AdminQueries/cognitoActions.js
> +    )
?

2023-05-26 11:32 UTC, andersrebner commented on cdk/backend/function/AdminQueries/db.js
> +  const lastUpdated = sortedByUpdated[0]
Kommentar på hva denne skal brukes til?

2023-05-26 11:37 UTC, andersrebner commented on cdk/backend/function/externalAPI/app.js
> +  getAnonUsers,
Skriv fullt format på anonymized

2023-05-26 11:47 UTC, andersrebner commented on cdk/backend/function/externalAPI/db.js
> +        { Name: 'isAnonymous', Value: true },
isAnonymized

2023-05-26 11:52 UTC, andersrebner commented on cdk/lib/kompetanse-stack.ts
> +        anonymizedID: new cognito.StringAttribute({ mutable: true }),
mutable false?

2023-05-26 11:58 UTC, andersrebner commented on cdk/test/adminqueries.db.test.ts
> +  const userScan = await docClient
await Promise.all

2023-05-26 12:03 UTC, andersrebner commented on cdk/test/adminqueries.db.test.ts
> +      Select: 'COUNT',
se om der det COUNT-es om det kan refaktoreres til én funksjon slik at det blir gjennbrukbart

2023-05-26 12:03 UTC, andersrebner commented on cdk/test/adminqueries.db.test.ts
> +      Select: 'COUNT',
hihi

2023-05-26 12:04 UTC, andersrebner commented on cdk/test/adminqueries.db.test.ts
> +      FilterExpression: '#owner = :karid',
kariID

2023-05-26 12:04 UTC, andersrebner commented on cdk/test/adminqueries.db.test.ts
> +  const kIdQAScan = await docClient
bedre navn

2023-05-26 12:04 UTC, andersrebner commented on cdk/test/adminqueries.db.test.ts
> +  const kIdQAScan = await docClient
):<

2023-05-26 12:07 UTC, andersrebner commented on cdk/test/adminqueries.test.ts
> +          ConsistentRead: false,
?

2023-05-26 12:11 UTC, andersrebner commented on cdk/test/common.ts
> +export const emptyAllDatabaseTables = async () => {
kan vi bruke dynamodb til å slette tabellene i sin helhet?

2023-05-26 12:12 UTC, andersrebner commented on cdk/test/testdata/dynamodb.items.ts
> +export const olaUserFormsInTestData = userFormTestData.filter(
flytt til common

2023-05-26 12:16 UTC, andersrebner commented on frontend/src/components/AdminPanel/AnonymizeUsers.tsx
> +      {error && <p>{t('errorOccured') + error}</p>}
trenger ikke begge error-ene?

2023-05-26 12:18 UTC, andersrebner commented on frontend/src/components/AdminPanel/adminApi.tsx
> +    console.log(e)
nei

2023-05-26 12:20 UTC, andersrebner commented on scripts/add_api_key_to_dynamodb.py
> +    full_table_name = table_name + '-' + "KompetanseStack" + '-' + env
revert

2023-05-26 12:21 UTC, andersrebner commented on scripts/create_users_to_anonymize.py
> +import random
delete

2023-05-26 12:51 UTC, synnovsh commented
takk for en fin pair code review anders 🤝

2023-05-26 13:12 UTC, synnovsh commented on cdk/backend/function/AdminQueries/cognitoActions.js
> +    )
det var prettier

2023-05-26 13:20 UTC, synnovsh commented on cdk/backend/function/AdminQueries/cognitoActions.js
> +    )
men ja-- det er riktig at en av oss la det på, og veldig usikker på hvem-- så spørsmål er om vi vil beholde eller ei!

2023-05-29 08:58 UTC, andersrebner commented on cdk/backend/function/AdminQueries/cognitoActions.js
> +    )
Jeg git blamer deg https://github.com/knowit/kompetansekartlegging-app/commit/5d9db01e2067b1f7271f551ceba66155788a39eb 😉 Tenker at vi kan fjerne det dersom du ikke kommer på en spes grunn til å legge det på

2023-05-29 10:01 UTC, andersrebner commented on cdk/backend/function/AdminQueries/app.js
> +  const user = await getUser(username)
Funksjonen `getUser` logger brukerens e-post. Lambda-loggen viser dermed e-post og UserForm-ID, slik at det vil være mulig å de-anonymisere brukeren i 90 dager (til lambda-loggen slettes). Det er ikke helt ideelt. Vil ikke fjerne loggingen, så legger på et funksjonsparameter `logUsername = true`
<img width="432" alt="Screenshot 2023-05-29 at 11 51 04" src="https://github.com/knowit/kompetansekartlegging-app/assets/72893130/21138fb2-a416-4f5b-b452-36f15c349aa7">

2023-06-01 10:44 UTC, krisstam requested changes
Ser bra ut dette :+1:

Kommentarene er hovedsaklig små-pirk, og jeg er åpen for å diskutere de også.

2023-06-01 10:44 UTC, krisstam commented on frontend/src/components/AdminPanel/AnonymizeUsers.tsx
> +  const anonymizeUser = (user: any) => {
Jeg er litt usikker på om jeg synes dette navnet kanskje var litt forvirrende.

Jeg kommer ikke på noe bedre selv, men det høres litt ut som om denne funksjonen gjør anonymizeUser uansett (kanskje? Det er også mulig at det ikke er noen særlig bedre måter å formulere den på)

Muligens burde den kanskje bare kalles "showAnonymizeUserDialog", men jeg er åpen for diskusjon

2023-06-01 10:44 UTC, krisstam requested changes
Ser bra ut dette :+1:

Kommentarene er hovedsaklig små-pirk, og jeg er åpen for å diskutere de også.

2023-06-01 12:19 UTC, synnovsh commented on cdk/backend/function/AdminQueries/db.js
> +          .update({
her brukte jeg `transactWrite()`

2023-06-04 14:51 UTC, krisstam commented on cdk/backend/function/AdminQueries/db.js
> +const batchAnonymizeOwner = (list, tableName, anonymizedID) => {
Nice :+1:

2023-06-04 14:56 UTC, krisstam approved these changes
Nå gikk jeg litt kjapt igjennom, men det virket som om dere har tatt tak i kommentarene mine fra sist.

Bra jobbet! Det er mulig jeg burde gå gjennom testene litt dypere, men fra det jeg så sist så virket de greie.

Approved 🎉

2023-06-06 12:09 UTC, merged